paths:
  data_path: "data/TSCO.csv"

df_structure:
  date: "Date"
  close: "Close"
  open: "Open"
  high: "High"
  low: "Low"
  adjclose: "Adj Close"
  volume: "Volume"

required_dirs:
  reports: ["results", "reports"]
  figures: ["results", "figures"]
  models: ["results", "models"]
  best_models: ["results", "best_models"]

data_engineering:
  fill_method: "polynomial"  # polynomial or linear
  poly_order: 2

technical_analysis:
  moving_avg_window: 10
  exp_moving_avg_window: 10
  money_flow_periods_window: 14
  macd_short_window: 12
  macd_long_window: 26
  signal_window: 9


data_files_type: "csv"

report_names:
  engineering: "data_engineering_report.txt"

feature2shift: "BTC_Close"

plotting_default:
  title_color: "#000000"
  title_font_style: "Arial"
  title_font_size: 20
  axes_line_width: 2
  axes_line_color: "#000000"
