stock_name:
  stock_name: "TSCO"

model_name:
  model_name: "BiLSTM"

paths:
  data_path: "data/TSCO.csv"

input_data_structure:
  date: "Date"
  close: "Close"
  open: "Open"
  high: "High"
  low: "Low"
  adjclose: "Adj Close"
  volume: "Volume"
  labels: "Labels"

features_in_use:
  features_in_use: ["Close", "Open", "High", "Low", "Volume", "MACD", "MFI"]

required_dirs:
  reports: ["results", "reports"]
  hyperparams: ["results", "hyperparams"]
  figures: ["results", "figures"]
  models: ["results", "models"]
  best_models: ["results", "best_models"]

data_engineering:
  fill_method: "polynomial"  # polynomial or linear
  poly_order: 2

data_exploration:
  correlation_method: "pearson"  # "pearson", "kendall" or "spearman"
  auto_correlation_lags: 24


technical_analysis:
  moving_avg_window: 10
  exp_moving_avg_window: 10
  money_flow_periods_window: 14
  macd_short_window: 12
  macd_long_window: 26
  signal_window: 9

label_tolerance:
  tolerance: 0.001

scaling:
  method: "standardscaler"  # "robust", "minmax" or "standardscaler"
  minmax_range: [0, 1]

plotting_default:
  title_color: "#000000"
  title_font_style: "Arial"
  title_font_size: 20
  axes_line_width: 2
  axes_line_color: "#000000"

forecast_horizon:
  horizon: 5

lstm_g_params:
  seed: 7
  epochs: 2
  batch_size: 32
  early_stopping_patience: 21
  activation_function: "tanh"
  reccurent_activation_func_function: "sigmoid"
  dense_activation: "relu"
  classification_activation: "softmax"

lstm_h_params:
  lstm_units_min: 10
  lstm_units_max: 20
  lstm_unit_step: 5
  dense_units_min: 10
  dense_units_max: 20
  dense_unit_step: 5
  drop_out_min: 0.2
  drop_out_max: 0.5
  drop_out_step: 3
  lr_min: 0.0001
  lr_max: 0.001
  lr_step: 3


